# -*- coding: utf-8 -*-

import os
from django.core.urlresolvers import reverse
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
from vvcatalog.models import Category

class Command(BaseCommand):
    help = 'Build routes for categories'

    def handle(self, *args, **options):
        categories = Category.objects.filter(status="published")
        print "Building routes for categories ..."
        u = reverse("category-index")
        ru = reverse("category-index-api")
        base = "page('"+u+"', function(ctx, next) { app.listCats('"+ru+"', '') } );"
        routes = [base]
        i = 1
        for category in categories:
            #url = reverse("category-detail", kwargs={'slug':category.slug})
            rest_url = reverse("category-detail-api", kwargs={'slug':category.slug})
            u = "page('"+category.url+"', function(ctx, next) { app.listCats('"+rest_url+"', '"+category.title+"') } );"
            routes.append(u)
            print str(i)+": "+category.url
            i += 1
        routes_str = '{# ************ Autogenerated file: do not edit ************ #}\n'+'\n'.join(routes)
        # check directories
        dirpath = settings.BASE_DIR+"/templates/vvcatalog"
        if not os.path.isdir(dirpath) is True:
            print "Creating directory templates/vvcatalog"
            os.makedirs(dirpath)
        dirpath = settings.BASE_DIR+"/templates/vvcatalog/auto"
        if not os.path.isdir(dirpath) is True:
            os.makedirs(dirpath)
            print "Creating directory templates/vvcatalog/auto"
        # update
        filepath=settings.BASE_DIR+"/templates/vvcatalog/auto/categories_routes.js"
        print "Updating templates/vvcatalog/auto/categories_routes.js"
        #~ write the file
        filex = open(filepath, "w")
        filex.write(routes_str)
        filex.close()
        print "OK: "+str(i-1)+" routes built "
        return
