title: "",
content: "",
header: '',
header_ori: "display:block",
footer: '',
footer_ori: "display:block",
vtitle: "title",
categories: [],
products:[],
noCats:"hidden",
currentCategory: "",
cart:[],
customerForm:"",
sumAccepted: false,
deliveryAccepted: false,
delivery: "",
customerFormPosted: false,
endCursor: "",
hasNextPage: false,