title: "",
content: "",
header: '',
header_ori: "display:block",
footer: '',
footer_ori: "display:block",
vtitle: "title",
categories: [],
products:[],
noCats:"hidden",
current_category: "",
cart:[],
cartTotal:-1,