# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vvcatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('edited', models.DateTimeField(auto_now=True, null=True, verbose_name='Edited')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=120, verbose_name='Status')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Order',
                'ordering': ('-created',),
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('edited', models.DateTimeField(auto_now=True, null=True, verbose_name='Edited')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price_per_unit', models.FloatField(verbose_name='Price per unit')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vvcatalog.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Ordered product',
                'ordering': ('-created', 'order'),
                'verbose_name_plural': 'Ordered products',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, upload_to='brands', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories', verbose_name='Navigation image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='civility',
            field=models.CharField(choices=[('mr', 'Mr'), ('mm', 'Mme')], default='mr', max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='navimage',
            field=models.ImageField(null=True, upload_to='products/nav/', verbose_name='Navigation image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered', to='vvcatalog.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vvcatalog.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Posted by'),
        ),
    ]
