# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 15:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vvcatalog', '0003_auto_20170418_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vvcatalog.Category', verbose_name='Category'),
        ),
    ]
