# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvcatalog', '0004_auto_20170418_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
