# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvcatalog', '0005_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
